### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Arkmull** [Birdgeek/BreadBot#1]
The run.bat just closes after this process shows up.
[INFO] [JDA] starting..

**Comment by Birdgeek** [comment]
try opening up a cmd prompt, cd-ing to the directory and typing `java -jar 0.0.6.jar'

Report back if that works out! I think i forgot the something in the batch file I uploaded

**Comment by Birdgeek** [comment]
[run.zip](https://github.com/Birdgeek/BreadBot/files/229088/run.zip) This is the fixed batch file for you as well
