### ISSUE TITLE
Am i missing something?

### ISSUE THREAD

**Issue by Bluscream** [Birdgeek/BreadBot#3]
![image](https://cloud.githubusercontent.com/assets/3318223/19227350/84a50c5e-8eb8-11e6-925f-b731655cf2c4.png)

![image](https://cloud.githubusercontent.com/assets/3318223/19227444/b9ffacc8-8eb9-11e6-8a84-70f0cfcf4b8b.png)

**Comment by Birdgeek** [comment]
You are not missing anything. I have not updated BreadBot and he is not verified working with the newer versions of Discord. If I find the time, I will rewrite him in a more streamlined manner and will hopefully work beautifully with the new Discord client.

**Comment by Bluscream** [comment]
@Birdgeek do you know any alternatives that are being maintained and preferably work on linux servers? :) (P.S. I tested it and it works fine [Except that i like to customize it a bit more ^^])

**Comment by Birdgeek** [comment]
None that I know of

**Comment by Bluscream** [comment]
@Birdgeek Can you give me some infos on the compiling process?

Should i use Eclipse?
Are there any dependencies/libraries that i need to import?
